feat(ci): streamline publish workflow by bumping version and tagging before build

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -24,37 +24,32 @@ jobs:
       - name: Install dependencies
         run: poetry install --no-root
 
-      - name: Try to Build and Publish
-        id: publish
+      - name: Bump version and Tag
+        id: versioning
+        run: |
+          # Bump version and get new version string
+          poetry version patch
+          NEW_VERSION=$(poetry version -s)
+          echo "New version: $NEW_VERSION"
+          git commit -am "Bump version to $NEW_VERSION"
+          git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
+          git push origin main --tags
+
+      - name: Build the package
+        run: poetry build
+
+      - name: Publish to PyPI
         env:
           PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
         run: |
-          set -e
-
-          # Define a function to attempt publish
-          attempt_publish() {
-            poetry build
-            poetry publish --username __token__ --password $PYPI_TOKEN
-          }
-
-          # Try initial publish
-          if ! attempt_publish; then
-            echo "Publishing failed, incrementing version and retrying..."
-            
-            # Bump version patch and retry
-            poetry version patch
-            NEW_VERSION=$(poetry version -s)
-            echo "New version: $NEW_VERSION"
-            git commit -am "Bump version to $NEW_VERSION"
-            git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
-            git push origin main --tags
-
-            # Retry publishing with the new version
-            attempt_publish
+          if [ -z "${{ secrets.PYPI_TOKEN }}" ]; then
+            echo "Error: PYPI_TOKEN is not set."
+            exit 1
           fi
+          poetry publish --username __token__ --password $PYPI_TOKEN
 
       - name: Create GitHub Release
-        uses: softprops/action-gh-release@v1
+        uses: softprops/action-gh-release@v1.1.0  # Atualizado para uma versão compatível com Node 20
         with:
           files: dist/*
           generate_release_notes: true
